/* 
 * File:   LIDAR_PWM.h
 * Author: paul
 * 
 * This header along with its source file provide functions to read a PWM signal generated by the 
 * LIDAR Lite V3 when operating in PWM mode.
 * 
 * It uses the SCCP4 peripheral in Input Capture mode to measure the pulse generated by LIDAR module.
 * A 32 bit timer is used.
 *
 * Created on March 4, 2017, 9:11 AM
 */

#ifndef LIDAR_PWM_H
#define	LIDAR_PWM_H

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef	__cplusplus
extern "C" {
#endif
    
    /**
     * Sets up the SCCP4 peripheral in input capture mode and clears the interrupts. 
     */
    void LIDAR_PWM_Initialize(void);




#ifdef	__cplusplus
}
#endif

#endif	/* LIDAR_PWM_H */

